version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
    - mvn clean 
    - mvn install 
  build:
    commands:
      - mvn package
artifacts:
  discard-paths: yes
  files:
    - target/*
    - scripts/*
    - appspec.yml
